### ISSUE TITLE
No source?

### ISSUE THREAD

**Issue by X3msnake** [TheContrappostoShop/PrometheusOS#15]
...

**Comment by ada-phillips** [comment]
Hi! I'm realizing now that it's not made super clear by the README, but this repo is intended to be build with [CustomPiOS](https://github.com/guysoft/CustomPiOS), and so most of the build logic lives in that repo. 

Aside from that, there is a link to the [Odyssey repo](https://github.com/TheContrappostoShop/Odyssey) (our custom control software) in the description, and from there a link to our [configuration repo](https://github.com/TheContrappostoShop/Prometheus_Config). I can try to clean up the README to make the dependencies clearer.
