### ISSUE TITLE
Problems encountered using 2024-06-14-1631-prometheusos-nanodlp-based-1.1.5.tar.xz

### ISSUE THREAD

**Issue by gengge** [TheContrappostoShop/PrometheusOS#20]
First of all thank you for sharing, let me learn a lot.
I discovered a bug where NanoDLP cannot be set to start automatically on boot. By modifying the file /etc/systemd/system/nanodlp.service and changing ExecStart=/home/pi/nanodlp/printer/printer, the problem is resolved.
I have a question, why do I get errors like Unknown command: "SET_RESIN_HEATER", Unknown command:"FSS_IDLE" , Unknown command: "SET_FIRST_BAR", and Unknown command: "TRIGGER" during printing?
I think the printer.cfg file is wrong. Can you provide the correct file?

**Comment by ada-phillips** [comment]
Hi! So sorry for the trouble, but I've identified the cause of your problems. We were a little hasty getting 1.1.5 out the door for Orion/Odyssey, that we didn't test NanoDLP build like we should've. Looks like one of our changes broke the unpacking process for the nanodlp release archive, and so the service file wasn't pointed to the right binary, and the config files weren't located correctly. 

I'll get this build tested ASAP and then backport to 1.1.5 release.

**Comment by gengge** [comment]
> Hi! So sorry for the trouble, but I've identified the cause of your problems. We were a little hasty getting 1.1.5 out the door for Orion/Odyssey, that we didn't test NanoDLP build like we should've. Looks like one of our changes broke the unpacking process for the nanodlp release archive, and so the service file wasn't pointed to the right binary, and the config files weren't located correctly.
> 
> I'll get this build tested ASAP and then backport to 1.1.5 release.

Thank you for your reply and look forward to the next update.
